theme: Jekyll
title: "ShipMank"
description: "Aplikasi pemesanan tiket rekreasi laut yang memudahkan wisatawan dalam memilih dan memesan kapal sesuai lokasi, waktu perjalanan, serta preferensi mereka. ShipMank menyediakan opsi kapal yang sudah terverifikasi kelayakan dan kualitasnya sehingga wisatawan dapat berlibur dengan aman dan nyaman."
